name: "\U0001F41B Bug Report"
description: Submit a bug report to help us improve EditorX / 提交一个 Bug 问题报告来帮助我们改进 EditorX
title: '[bug] '
labels:
  - 'bug'
body:
  - type: input
      id: editorx-version
      attributes:
        label: EditorX version / EditorX 版本号
      validations:
        required: true
  - type: input
    id: java-version
    attributes:
      label: Java version / Java 版本号
    validations:
      required: true
  - type: checkboxes
    id: os
    attributes:
      label: OS / 操作系统
      options:
        - label: Windows
        - label: Linux
        - label: macOS
  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Reproduction / 复现过程
      description: "Steps to reproduce the behavior. /复现Bug的步骤。"
  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: Expected behavior / 期待表现
      description: "A clear and concise description of what you would expect to happen. /简单描述您期望发生的事情。"